-- ============================================================================
-- GÉNÉRATEUR : Commandes ALTER FUNCTION avec signatures complètes
-- ============================================================================
-- Ce script génère automatiquement les commandes ALTER FUNCTION
-- avec les signatures complètes pour toutes les fonctions sans search_path
-- ============================================================================
-- Date : 2025-01-29
-- ============================================================================

-- Afficher toutes les commandes ALTER FUNCTION nécessaires
SELECT 
    'ALTER FUNCTION ' ||
    quote_ident(n.nspname) || '.' || quote_ident(p.proname) ||
    '(' ||
    pg_get_function_arguments(p.oid) ||
    ') SET search_path = '''';' as alter_command
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public'
AND p.proname IN (
    'update_document_file_permission_updated_at',
    'increment_document_file_download_count',
    'update_calendar_updated_at',
    'get_client_files',
    'trigger_cleanup_expired_sessions',
    'update_import_mapping_config_updated_at',
    'update_import_templates_updated_at',
    'update_expert_client_emails_timestamp',
    'update_expert_client_emails_received_timestamp',
    'update_expert_client_email_sequences_timestamp',
    'update_expert_client_email_scheduled_timestamp',
    'mark_notification_unread',
    'create_notification_status_for_all_admins',
    'get_client_file_stats',
    'cleanup_expired_files',
    'create_recurring_events',
    'set_notification_expiration',
    'create_admin_conversation',
    'update_conversation_last_message',
    'cleanup_old_typing_indicators',
    'calculer_montant_produit',
    'update_reminder_updated_at',
    'update_ged_document_last_modified',
    'update_ged_document_permission_updated_at',
    'get_ged_document_permissions',
    'get_ged_user_documents',
    'check_bucket_permissions',
    'log_bucket_access',
    'check_document_access',
    'log_admin_action',
    'get_documents_stats',
    'update_audit_documents_updated_at',
    'get_rdv_end_datetime',
    'update_document_file_updated_at',
    'increment_download_count',
    'cleanup_expired_shares',
    'get_user_document_stats',
    'update_prospect_email_received_timestamp',
    'update_prospect_reports_timestamp',
    'save_prospect_report_version',
    'trigger_update_dossier_progress',
    'get_admin_audit_history',
    'update_documentation_items_updated_at',
    'update_notification_final_updated_at',
    'create_document_version',
    'get_client_document_size',
    'get_expired_documents',
    'get_document_stats',
    'update_prospects_updated_at',
    'update_updated_at_column',
    'update_prospect_emailing_status',
    'migrate_simulator_to_client',
    'migrate_simulator_to_existing_client',
    'create_client_admin_conversation',
    'get_overdue_controls',
    'get_recent_security_incidents',
    'update_documentation_updated_at',
    'increment_documentation_view_count',
    'create_expert_admin_conversation',
    'cleanup_old_candidatures',
    'get_actions_by_type',
    'get_apporteur_kpis',
    'get_rdv_status_label',
    'get_top_experts',
    'get_expert_global_stats',
    'update_expert_assignment_updated_at',
    'notify_prospect_reply',
    'log_dossier_change',
    'trigger_log_expert_changes',
    'clean_expired_sessions',
    'calculate_eligibility',
    'update_simulation_history_updated_at',
    'trigger_update_expert_stats',
    'trigger_update_expert_earnings',
    'update_rdv_updated_at',
    'update_message_updated_at',
    'generate_message_thread_id',
    'create_simulator_session_with_client_data',
    'insert_ticpe_questions_transaction',
    'cleanup_expired_temporary_data',
    'update_email_tracking_timestamp',
    'cabinet_set_updated_at',
    'extract_email_domain',
    'check_prospect_email_match',
    'merge_client_products',
    'cleanup_expired_simulator_sessions',
    'stop_prospect_sequences_on_reply',
    'test_expert_global_stats',
    'migrate_session_manually',
    'update_expert_campaign_updated_at',
    'check_campaign_dates',
    'update_campaign_active_status',
    'get_expert_assignments_by_status',
    'clean_old_email_trackings',
    'notify_prospect_reply_enhanced',
    'mark_session_completed',
    'update_session_activity',
    'update_expert_criteria_updated_at',
    'rdv_report_set_updated_at',
    'calculer_tous_produits',
    'calculer_multiplication_sequence',
    'mark_notification_as_read',
    'mark_notification_as_dismissed',
    'cleanup_expired_notifications',
    'rdv_task_set_updated_at',
    'recalculate_scheduled_emails_dates',
    'update_admin_notification_updated_at',
    'update_notification_updated_at',
    'get_notification_stats',
    'get_rdv_stats',
    'cleanup_old_historique',
    'migrate_session_manually_corrected',
    'detect_suspicious_activity',
    'cleanup_old_access_logs',
    'get_auth_user_id_by_email',
    'generate_email_content_hash',
    'set_email_content_hash',
    'is_email_already_sent',
    'cabinet_set_slug',
    'refresh_cabinet_team_stat',
    'get_assignment_statistics',
    'get_simulation_results',
    'cabinet_produit_set_updated_at',
    'update_promotion_banner_updated_at',
    'check_banner_dates',
    'update_banner_active_status',
    'increment_banner_impressions',
    'increment_banner_clicks',
    'create_client',
    'generate_client_id',
    'generate_expert_id',
    'get_user_details',
    'get_user_type',
    'update_chatbot_log_updated_at',
    'update_eligibility_changes_updated_at',
    'update_shared_document_timestamp',
    'update_document_request_updated_at',
    'update_contact_messages_updated_at',
    'create_temporary_client',
    'archive_orphan_parents',
    'update_apporteur_updated_at',
    'migrate_temporary_client',
    'update_client_process_document_updated_at',
    'cleanup_inactive_fcm_tokens',
    'save_simulator_responses',
    'calculate_simulator_eligibility',
    'create_system_comment',
    'create_hot_prospect',
    'convert_prospect_to_client',
    'get_apporteur_activite_personnelle',
    'sync_documents_sent',
    'trigger_status_change_comment',
    'get_apporteur_prospects_detaille',
    'trigger_rdv_comment',
    'calculate_expert_stats',
    'mark_notification_read',
    'get_apporteur_alertes_personnelles',
    'create_simulation_with_temporary_client',
    'update_all_expert_stats',
    'archive_notification',
    'mapper_reponses_vers_variables',
    'trigger_document_comment',
    'update_client_charte_signature_updated_at',
    'cleanup_old_notifications',
    'check_inactivity_alerts',
    'calculer_percentage',
    'initialize_admin_notification_status',
    'mark_admin_notification_read',
    'archive_admin_notification',
    'cleanup_old_admin_notifications',
    'update_dossier_timeline_updated_at',
    'validate_admin_notification_data',
    'validate_notification_data',
    'auto_archive_expired_notifications',
    'manage_parent_child_relationships',
    'duplicate_completed_simulation',
    'update_parent_children_count',
    'update_document_version',
    'initialize_apporteur_notification_status',
    'cleanup_old_apporteur_notifications',
    'update_apporteur_notification_updated_at',
    'validate_apporteur_notification_data',
    'mark_apporteur_notification_read',
    'archive_apporteur_notification',
    'initialize_client_notification_status',
    'cleanup_old_client_notifications',
    'update_client_notification_updated_at',
    'validate_client_notification_data',
    'mark_client_notification_read',
    'archive_client_notification',
    'sync_apporteur_notification_is_read',
    'sync_client_notification_is_read',
    'update_dossier_progress_from_steps',
    'evaluer_eligibilite_avec_calcul',
    'create_conversation_direct'
)
AND (p.proconfig IS NULL OR array_to_string(p.proconfig, ',') NOT LIKE '%search_path%')
ORDER BY p.proname;
