-- Script pour créer 10 experts avec des spécialisations multiples
-- Correspondant aux produits éligibles : CEE, DFS, Foncier, MSA, Optimisation Énergie, TICPE, URSSAF

-- Nettoyage préalable (optionnel - décommentez si nécessaire)
-- DELETE FROM "Expert" WHERE email LIKE '%demo%';

-- Insertion des experts
INSERT INTO "Expert" (
    id,
    email,
    password,
    name,
    company_name,
    siren,
    specializations,
    experience,
    location,
    rating,
    compensation,
    description,
    status,
    disponibilites,
    certifications,
    card_number,
    card_expiry,
    card_cvc,
    abonnement,
    auth_id,
    created_at,
    updated_at
) VALUES
-- Expert 1 : Spécialisé TICPE + URSSAF
(
    gen_random_uuid(),
    'jean.dupont@cabinet-fiscal-plus.fr',
    '$2a$10$demo_password_hash',
    'Jean Dupont',
    'Cabinet Fiscal Plus',
    '123456789',
    ARRAY['TICPE', 'URSSAF'],
    '15 ans d''expérience en optimisation fiscale et sociale',
    'Paris',
    4.8,
    18.5,
    'Expert reconnu en optimisation fiscale avec une expertise particulière en TICPE et URSSAF. Plus de 200 dossiers traités avec succès.',
    'active',
    '{"lundi": "9h-17h", "mardi": "9h-17h", "mercredi": "9h-17h", "jeudi": "9h-17h", "vendredi": "9h-17h"}',
    '["Certification Expert-Comptable", "Certification URSSAF", "Certification TICPE"]',
    NULL,
    NULL,
    NULL,
    'scale',
    NULL,
    NOW(),
    NOW()
),

-- Expert 2 : Spécialisé DFS + Foncier
(
    gen_random_uuid(),
    'marie.laurent@social-experts.fr',
    '$2a$10$demo_password_hash',
    'Marie Laurent',
    'Social Experts',
    '987654321',
    ARRAY['DFS', 'Foncier'],
    '12 ans d''expérience en fiscalité et optimisation sociale',
    'Lyon',
    4.9,
    22.0,
    'Spécialiste des questions fiscales et sociales, expert en DFS et optimisation foncière. Accompagnement personnalisé et résultats garantis.',
    'active',
    '{"lundi": "8h-18h", "mardi": "8h-18h", "mercredi": "8h-18h", "jeudi": "8h-18h", "vendredi": "8h-16h"}',
    '["Certification DFS", "Certification Foncier", "Certification Sociale"]',
    NULL,
    NULL,
    NULL,
    'scale',
    NULL,
    NOW(),
    NOW()
),

-- Expert 3 : Spécialisé CEE + Optimisation Énergie
(
    gen_random_uuid(),
    'pierre.martin@cabinet-martin-associes.fr',
    '$2a$10$demo_password_hash',
    'Pierre Martin',
    'Cabinet Martin & Associés',
    '456789123',
    ARRAY['CEE', 'Optimisation Énergie'],
    '10 ans d''expérience en crédits d''impôts et optimisations énergétiques',
    'Marseille',
    4.7,
    16.5,
    'Expert en crédits d''impôts et optimisations énergétiques. Spécialiste des certificats d''économies d''énergie et de l''optimisation des contrats.',
    'active',
    '{"lundi": "9h-17h", "mardi": "9h-17h", "mercredi": "9h-17h", "jeudi": "9h-17h", "vendredi": "9h-17h"}',
    '["Certification CEE", "Certification Énergie", "Certification Crédits d''Impôts"]',
    NULL,
    NULL,
    NULL,
    'growth',
    NULL,
    NOW(),
    NOW()
),

-- Expert 4 : Spécialisé TICPE + CIR + CEE
(
    gen_random_uuid(),
    'sophie.dubois@dubois-consulting.fr',
    '$2a$10$demo_password_hash',
    'Sophie Dubois',
    'Dubois Consulting',
    '789123456',
    ARRAY['TICPE', 'CEE', 'DFS'],
    '18 ans d''expérience en fiscalité et optimisation',
    'Bordeaux',
    4.9,
    25.0,
    'Consultante senior en fiscalité et optimisation. Expertise complète en TICPE, CEE et DFS. Plus de 500 dossiers traités.',
    'active',
    '{"lundi": "8h-18h", "mardi": "8h-18h", "mercredi": "8h-18h", "jeudi": "8h-18h", "vendredi": "8h-18h"}',
    '["Certification Senior", "Certification TICPE", "Certification CEE", "Certification DFS"]',
    NULL,
    NULL,
    NULL,
    'scale',
    NULL,
    NOW(),
    NOW()
),

-- Expert 5 : Spécialisé URSSAF + MSA
(
    gen_random_uuid(),
    'thomas.bernard@bernard-social.fr',
    '$2a$10$demo_password_hash',
    'Thomas Bernard',
    'Bernard Social',
    '321654987',
    ARRAY['URSSAF', 'MSA'],
    '8 ans d''expérience en fiscalité sociale et optimisations',
    'Lille',
    4.6,
    14.5,
    'Expert en fiscalité sociale et optimisations URSSAF et MSA. Accompagnement des entreprises agricoles et commerciales.',
    'active',
    '{"lundi": "9h-17h", "mardi": "9h-17h", "mercredi": "9h-17h", "jeudi": "9h-17h", "vendredi": "9h-17h"}',
    '["Certification URSSAF", "Certification MSA", "Certification Sociale"]',
    NULL,
    NULL,
    NULL,
    'growth',
    NULL,
    NOW(),
    NOW()
),

-- Expert 6 : Spécialisé Foncier + DFS
(
    gen_random_uuid(),
    'anne.roussel@cabinet-roussel.fr',
    '$2a$10$demo_password_hash',
    'Anne Roussel',
    'Cabinet Roussel',
    '654321987',
    ARRAY['Foncier', 'DFS'],
    '11 ans d''expérience en fiscalité foncière',
    'Nantes',
    4.5,
    19.0,
    'Spécialiste en fiscalité foncière et DFS. Expertise particulière pour les investisseurs immobiliers et les entreprises.',
    'active',
    '{"lundi": "8h-17h", "mardi": "8h-17h", "mercredi": "8h-17h", "jeudi": "8h-17h", "vendredi": "8h-17h"}',
    '["Certification Foncier", "Certification DFS", "Certification Immobilier"]',
    NULL,
    NULL,
    NULL,
    'growth',
    NULL,
    NOW(),
    NOW()
),

-- Expert 7 : Spécialisé Optimisation Énergie + CEE
(
    gen_random_uuid(),
    'luc.moreau@moreau-energie.fr',
    '$2a$10$demo_password_hash',
    'Luc Moreau',
    'Moreau Énergie',
    '147258369',
    ARRAY['Optimisation Énergie', 'CEE'],
    '13 ans d''expérience en optimisation énergétique',
    'Toulouse',
    4.8,
    21.5,
    'Expert en optimisation énergétique et certificats d''économies d''énergie. Accompagnement des entreprises dans leur transition énergétique.',
    'active',
    '{"lundi": "9h-18h", "mardi": "9h-18h", "mercredi": "9h-18h", "jeudi": "9h-18h", "vendredi": "9h-18h"}',
    '["Certification Énergie", "Certification CEE", "Certification Transition Énergétique"]',
    NULL,
    NULL,
    NULL,
    'scale',
    NULL,
    NOW(),
    NOW()
),

-- Expert 8 : Spécialisé TICPE + DFS + URSSAF
(
    gen_random_uuid(),
    'camille.leroy@leroy-fiscal.fr',
    '$2a$10$demo_password_hash',
    'Camille Leroy',
    'Leroy Fiscal',
    '963852741',
    ARRAY['TICPE', 'DFS', 'URSSAF'],
    '16 ans d''expérience en fiscalité et optimisation',
    'Strasbourg',
    4.7,
    23.0,
    'Expert polyvalent en fiscalité et optimisation. Spécialiste TICPE, DFS et URSSAF. Accompagnement complet des entreprises.',
    'active',
    '{"lundi": "8h-18h", "mardi": "8h-18h", "mercredi": "8h-18h", "jeudi": "8h-18h", "vendredi": "8h-18h"}',
    '["Certification TICPE", "Certification DFS", "Certification URSSAF", "Certification Polyvalente"]',
    NULL,
    NULL,
    NULL,
    'scale',
    NULL,
    NOW(),
    NOW()
),

-- Expert 9 : Spécialisé MSA + Foncier
(
    gen_random_uuid(),
    'julie.petit@petit-agricole.fr',
    '$2a$10$demo_password_hash',
    'Julie Petit',
    'Petit Agricole',
    '852963741',
    ARRAY['MSA', 'Foncier'],
    '9 ans d''expérience en secteur agricole',
    'Dijon',
    4.4,
    17.5,
    'Spécialiste du secteur agricole et de l''optimisation MSA. Expertise en fiscalité foncière pour les exploitants agricoles.',
    'active',
    '{"lundi": "9h-17h", "mardi": "9h-17h", "mercredi": "9h-17h", "jeudi": "9h-17h", "vendredi": "9h-17h"}',
    '["Certification MSA", "Certification Foncier", "Certification Agricole"]',
    NULL,
    NULL,
    NULL,
    'starter',
    NULL,
    NOW(),
    NOW()
),

-- Expert 10 : Spécialisé CEE + Optimisation Énergie + DFS
(
    gen_random_uuid(),
    'marc.durand@durand-eco.fr',
    '$2a$10$demo_password_hash',
    'Marc Durand',
    'Durand Éco',
    '741852963',
    ARRAY['CEE', 'Optimisation Énergie', 'DFS'],
    '14 ans d''expérience en développement durable et fiscalité',
    'Grenoble',
    4.6,
    20.0,
    'Expert en développement durable et fiscalité verte. Spécialiste CEE, optimisation énergétique et DFS pour entreprises éco-responsables.',
    'active',
    '{"lundi": "8h-17h", "mardi": "8h-17h", "mercredi": "8h-17h", "jeudi": "8h-17h", "vendredi": "8h-17h"}',
    '["Certification CEE", "Certification Énergie", "Certification DFS", "Certification Développement Durable"]',
    NULL,
    NULL,
    NULL,
    'growth',
    NULL,
    NOW(),
    NOW()
);

-- Vérification de l'insertion
SELECT 
    name,
    company_name,
    specializations,
    rating,
    compensation,
    status,
    abonnement
FROM "Expert" 
WHERE email LIKE '%demo%' OR email LIKE '%@%'
ORDER BY name; 